// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADucnW8NJD8z8TixfqZDwO8mpJjrtclgc',
    appId: '1:179783851533:web:51c09932096ef30b623f44',
    messagingSenderId: '179783851533',
    projectId: 'prueba-fd643',
    authDomain: 'prueba-fd643.firebaseapp.com',
    storageBucket: 'prueba-fd643.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6unW1YE3k2vG30z3NbBNZP98JWtHeCC0',
    appId: '1:179783851533:android:34d39989c5f950e6623f44',
    messagingSenderId: '179783851533',
    projectId: 'prueba-fd643',
    storageBucket: 'prueba-fd643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARVUtki_BCMCquhQb8iYwDJBUyRIPvSvE',
    appId: '1:179783851533:ios:37690064ac036a4a623f44',
    messagingSenderId: '179783851533',
    projectId: 'prueba-fd643',
    storageBucket: 'prueba-fd643.appspot.com',
    iosBundleId: 'com.example.miltonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARVUtki_BCMCquhQb8iYwDJBUyRIPvSvE',
    appId: '1:179783851533:ios:37690064ac036a4a623f44',
    messagingSenderId: '179783851533',
    projectId: 'prueba-fd643',
    storageBucket: 'prueba-fd643.appspot.com',
    iosBundleId: 'com.example.miltonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADucnW8NJD8z8TixfqZDwO8mpJjrtclgc',
    appId: '1:179783851533:web:8658bbac3298b0fb623f44',
    messagingSenderId: '179783851533',
    projectId: 'prueba-fd643',
    authDomain: 'prueba-fd643.firebaseapp.com',
    storageBucket: 'prueba-fd643.appspot.com',
  );
}
